### ISSUE TITLE
[feature] Add support for aliases

### ISSUE THREAD

**Issue by tranzystorekk** [mattmahn/gitall.rs#11]
`git-foo` plugins are nice, but seem like an overkill for most `gitall` applications. I'd like to propose a feature similar to `git` and `github-cli` aliases, where a user can set a short alias for a `git` command and  its arguments in a config file, e.g.

```toml
[aliases]
fa = "fetch --all --prune"
```

and then just call `gitall fa` to do a fetch-with-prune
